CREATE TABLE "levels" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "level" varchar NOT NULL
);

CREATE TABLE "course_videos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(30) NOT NULL,
  "url" varchar(50) NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL,
  "email" varchar(50) NOT NULL,
  "password" varchar(30) NOT NULL,
  "age" int NOT NULL,
  "rol_id" int NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(30) NOT NULL,
  "description" varchar(50) NOT NULL,
  "teacher" varchar(30) NOT NULL,
  "category_id" int NOT NULL,
  "course_video_id" int NOT NULL
);

CREATE TABLE "users_courses" (
  "user_id" int NOT NULL,
  "course_id" int NOT NULL
);

CREATE TABLE "courses_levels" (
  "course_id" int NOT NULL,
  "level_id" int NOT NULL
);

ALTER TABLE "courses_levels" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "courses_levels" ADD FOREIGN KEY ("level_id") REFERENCES "levels" ("id");

ALTER TABLE "users" ADD FOREIGN KEY ("rol_id") REFERENCES "roles" ("id");

ALTER TABLE "users_courses" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "users_courses" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("course_video_id") REFERENCES "course_videos" ("id");




INSERT INTO levels (level) VALUES  ('beginner'),  ('intermediate'), ('advanced');
INSERT INTO course_videos (title, url) VALUES  ('01', 'abc'),  ('02', 'def'), ('03', 'ghi');
INSERT INTO categories (name) VALUES  ('illustration'),  ('marketing and business'), ('architecture and space');
INSERT INTO roles (name) VALUES  ('student'),  ('teacher'), ('admin');
INSERT INTO users (name, email, password, age, rol_id) VALUES  ('Sandy', 'sandy@email.com', 'asd', '24', 2), ('David', 'david@email.com', 'asd', '18', 1),  ('Daniel', 'daniel@email.com', 'asd', '30', 3);
INSERT INTO courses (title, description, teacher, category_id, course_video_id) VALUES  ('Introduccion Illustrator', 'Aprende Adobe Illustrator, crea gráficos', 'Aaron Martinez', 4, 1);
INSERT INTO courses (title, description, teacher, category_id, course_video_id) VALUES  ('Finanzas pequeñas empresas', 'Aprende metas presupuestarias', 'Clare Seal', 5, 1);
INSERT INTO courses (title, description, teacher, category_id, course_video_id) VALUES ('Modelado arquitectonico 3D', 'Paso a paso metodologia BIM', 'Arturo Bustios', 6, 1);
INSERT INTO users_courses (user_id, course_id) VALUES  (2, 3),  (3, 1), (4, 2);
INSERT INTO users_courses (user_id, course_id) VALUES  (2, 2);
INSERT INTO users_courses (user_id, course_id) VALUES  (4, 1), (4, 3);
INSERT INTO courses_levels (course_id, level_id) VALUES  (1, 1),  (1, 2), (1, 3), (2, 1),  (2, 2), (2, 3), (3, 1),  (3, 2), (3, 3);




